#!/bin/sh

fn_start() {
    if fn_is_running; then
        echo "Service $NAME is already running" >&2
        return 1
    fi

    fn_validate_config || return 1
    fn_create_session_if_required || return 1

    fn_acquire_tun_interface || return 1
    fn_up_tun_interface || return 1
    fn_create_running_config

    start-stop-daemon -S -bmc "$USER" -p "$PIDFILE" -x "$USQUE_BIN" -- $(fn_daemon_args) || {
        echo "Failed to start $NAME service"

        fn_down_tun_interface
        fn_remove_running_config
        rm -f "$PIDFILE"
        return 1
    }

    echo "Started $NAME service"
}

fn_stop() {
    if ! fn_is_running; then
        echo "Service $NAME is not running" >&2
        return 1
    fi

    echo "Stopping $NAME service..."
    fn_down_tun_interface
    fn_remove_running_config

    # kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    start-stop-daemon -K -p "$PIDFILE" && rm -f "$PIDFILE"
}

fn_acquire_if() {
    if fn_is_running; then
        echo "Cannot perform while service $NAME is running" >&2
        return 1
    fi

    fn_acquire_tun_interface
}

fn_release_if() {
    if fn_is_running; then
        echo "Cannot perform while service $NAME is running" >&2
        return 1
    fi

    fn_release_tun_interface
}

case "$1" in
start)
    fn_start
    ;;
stop)
    fn_stop
    ;;
status)
    fn_status
    ;;
restart)
    fn_stop
    fn_start
    ;;
acquire-if)
    fn_acquire_if
    ;;
release-if)
    fn_release_if
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status|acquire-if|release-if}"
    ;;
esac
