# Interface for USQUE (e.g., OpkgTun0).
# By default, the interface will be selected automatically.
# IFACE="OpkgTun0"

# Interface IP address.
# By default, the first free address in the range
# 172.16.1.100 - 172.16.1.200 will be selected.
# IFACE_IP="172.16.0.1"

# Subnet mask. Default is 255.255.255.255
# IFACE_MASK="255.255.255.255"

# SNI for traffic masking
SNI="ozon.ru"

# User under whose privileges the daemon will run
USER=nobody

# Configuration version
# DO NOT CHANGE THIS VALUE
CONFIG_VERSION=1

